{% set version = "2.11.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-exposition
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ExPosition_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ExPosition/ExPosition_{{ version }}.tar.gz
  sha256: f9c9f49ab94b0b5700e9db5a456ef279544c75e1d92ba55cebd4f8ff17de0bd3

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-prettygraphs >=2.1.4
  run:
    - r-base
    - r-prettygraphs >=2.1.4

test:
  commands:
    - $R -e "library('ExPosition')"           # [not win]
    - "\"%R%\" -e \"library('ExPosition')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ExPosition
  license: GPL-2
  summary: A variety of descriptive multivariate analyses with the singular value decomposition, such as principal components analysis, correspondence analysis, and multidimensional scaling. See An ExPosition of the Singular Value Decomposition in R (Beaton et al 2014) <doi:10.1016/j.csda.2013.11.006>.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ExPosition
# Type: Package
# Title: Exploratory Analysis with the Singular Value Decomposition
# Version: 2.8.23
# Date: 2018-12-27
# Author: Derek Beaton, Cherise R. Chin Fatt, Herve Abdi
# Maintainer: Derek Beaton <exposition.software@gmail.com>
# Description: A variety of descriptive multivariate analyses with the singular value decomposition, such as principal components analysis, correspondence analysis, and multidimensional scaling. See An ExPosition of the Singular Value Decomposition in R (Beaton et al 2014) <doi:10.1016/j.csda.2013.11.006>.
# License: GPL-2
# Depends: prettyGraphs (>= 2.1.4)
# Packaged: 2018-12-27 16:16:04 UTC; Derek
# BugReports: https://github.com/derekbeaton/ExPosition-Family_OLD
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2019-01-07 17:00:41 UTC
