appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: R9lusgprV4uGgwpJy+k10W0ELBpV6Rbt7/ahU9a2rdWwlxusWsIT/KL/PjYFieXDFAzzOp6rjThzhzKP1KNxJ5TxY6H+NPHakrw5LGXRYAbtMmBy7+VfznH3G1d33uA7989JIFH4XP51onBzTEd16XbBbDi4IMoYDfboLR94iqK/Ze27MJxd7qywygeuMfwN1TNKXBR4UobvzkjhhC47XHT3ArptHessGUx83Ku2IzjesInT3lUQb8pss1tiTbLqgfZzQZ+fvtlnrmn9Rd69yS+pbbizTFK99Aa/o2JaDGqmlU3GDCw2vO5eCcbBrh0vnj/zvHI4AIP7btMFJ27vM4y4fTbfGzRrJ0nfU6YH8t9ikA9eWhhXjvfwbJEmgcBorLCcDJYGxto8BfmVXaiBAaFTmEo+6hdy6xXNfK7ksVEo8fNbHYLN7yaiEZT+TVyCU7+zxNort1C1UcqjuDUBG5G3YRWSgsfOsk7m7j+XgnOG2gHsech0ef+jnDnqTR9FLvmp4G3MvOypANk6lXt9e20oXk/2gntmSAUX32RnD9YIxnBxaBduyix1lxgiwpmVZADR1z4YmGD3WGR46uIyo0yI2rkijFvUzmyfC8jekbK7wM2fVsbw04AgnYWF7B3yXd0uAzPVIwpGnAntBwyUGy0pj5d/Ib9er4h3XSezXW8=
